LOGIN_URL = "https://practicetestautomation.com/practice-test-login/"
USERNAME_VALID = "student"
USERNAME_INVALID = "incorrectUser"
PASSWORD_VALID = "Password123"
PASSWORD_INVALID = "incorrectPassword"